name: Deploy to Timeweb (dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Загружаем nvm (нужно для доступа к npm и pm2)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # Переходим в папку с проектом
            cd /root/kora-back

            # Забираем последние изменения из ветки dev
            git pull origin dev

            # Устанавливаем зависимости
            npm ci

            # Генерируем Prisma Client
            npx prisma generate

            # Собираем проект
            npm run build

            # Применяем миграции
            npx prisma migrate deploy

            # Перезапускаем приложение
            pm2 restart kora-back
